create loan calculcator
nikitapleshkanov/qa-automation-java pull request #4
Opened 2021-08-15 12:06 UTC by nikitapleshkanov

2021-08-16 14:14 UTC, pshakhov requested changes

2021-08-16 14:15 UTC, nikitapleshkanov commented on src/main/java/com/tinkoff/edu/test/LoanCalcTest.java
> +public class LoanCalcTest {
да

2021-08-16 14:19 UTC, nikitapleshkanov commented on src/main/java/com/tinkoff/edu/app/LoanCalcRepository.java
> +    public static int requestId;
просто установить private достаточно будет ?

2021-08-17 06:18 UTC, pshakhov commented on src/main/java/com/tinkoff/edu/app/LoanCalcLogger.java
> +
небольшая придирка - пустая строка между жавадоком и классом на самом деле не нужна, обычно он прямо над

2021-08-17 06:18 UTC, pshakhov approved these changes

2021-08-17 07:09 UTC, merged