add buisness logic and some tests
nikitapleshkanov/qa-automation-java pull request #8
Opened 2021-08-30 13:13 UTC by nikitapleshkanov

2021-08-30 14:15 UTC, pshakhov requested changes

2021-08-30 14:15 UTC, pshakhov commented on src/test/java/com/tinkoff/edu/AppTest.java
> +    @DisplayName("Проверка одобрения заявки: loanType = PERSON, amount > 10000, months > 12")
может сбить с толку - лучше явно указать ожидаемый результат - отклонение
```suggestion
    @DisplayName("Проверка отклонения заявки: loanType = PERSON, amount > 10000, months > 12")
```

2021-08-30 14:15 UTC, pshakhov commented on src/test/java/com/tinkoff/edu/AppTest.java
> +    public void checkApproveRequestForPerson2() {
в нейминге тоже лучше явно указать ожидаемый результат - declineRequestIfMoreThanYear(Test) (грубо говоря)

2021-08-30 14:15 UTC, pshakhov commented on src/test/java/com/tinkoff/edu/AppTest.java
> +    @DisplayName("Проверка одобрения заявки: loanType = OOO, amount <= 10000,  months > 12")
```suggestion
    @DisplayName("Проверка отклонения заявки: loanType = OOO, amount <= 10000,  months > 12")
```

2021-08-30 14:15 UTC, pshakhov commented on src/test/java/com/tinkoff/edu/AppTest.java
> +    @DisplayName("Проверка одобрения заявки: loanType = OOO, amount <= 10000, months <= 12")
```suggestion
    @DisplayName("Проверка отклонения заявки: loanType = OOO, amount <= 10000, months <= 12")
```

2021-08-30 14:15 UTC, pshakhov commented on src/test/java/com/tinkoff/edu/AppTest.java
> +    private void finalCheck(LoanResponseType expectedLoanType, LoanResponse loanResponse) {
не стоит, лучше использовать нативный, под капот все равно практически никаких упрощений не заехало
```suggestion
    assertEquals(expectedLoanType, loanResponse.getIsAccepted());
```

2021-08-30 14:15 UTC, pshakhov commented on src/test/java/com/tinkoff/edu/AppTest.java
> +        Assertions.assertEquals(expectedLoanType, loanResponse.getIsAccepted());
Assertions.assertEquals можно в импорты затянуть, тогда ассерт можно будет вызвать без точки

2021-08-30 15:48 UTC, nikitapleshkanov commented on src/test/java/com/tinkoff/edu/AppTest.java
> +    public void checkApproveRequestForPerson2() {
получается тогда надо использовать название checkApproveRequestForPersonMoreThenYearMoreThen10k ?есть ли смысл так каждый кейс переименовывать ?

2021-08-30 15:49 UTC, nikitapleshkanov commented on src/test/java/com/tinkoff/edu/AppTest.java
> +    private void finalCheck(LoanResponseType expectedLoanType, LoanResponse loanResponse) {
не понял к чему этот коммент и что мне надо поправить

2021-08-30 16:09 UTC, pshakhov commented on src/test/java/com/tinkoff/edu/AppTest.java
> +    public void checkApproveRequestForPerson2() {
не, такое название слишком сложное (кто-то вообще по-русски даже пишет типа `одобрение до года с лимитом 10к`)
но мы так делать не будем

2021-08-30 16:33 UTC, pshakhov commented on src/test/java/com/tinkoff/edu/AppTest.java
> +        loanResponse.printLoanResponseInfo();
если занести loanResponse.printLoanResponseInfo() капот, код сократился бы еще на 10-15 строк

2021-08-30 16:56 UTC, nikitapleshkanov commented on src/test/java/com/tinkoff/edu/AppTest.java
> +        loanResponse.printLoanResponseInfo();
да по идее это же для теста ненужный вызов, а скорее для бизнесс логики
из тестово его надо убрать

2021-08-30 16:56 UTC, nikitapleshkanov commented on src/test/java/com/tinkoff/edu/AppTest.java
> +        loanResponse.printLoanResponseInfo();
сейчас и уберу 🤔

2021-08-31 06:35 UTC, pshakhov approved these changes
в целом все хорошо, с покрытием разбираемся в следующем реквесте

2021-09-01 17:00 UTC, merged